### ISSUE TITLE
{{ a if b else c }} breaks syntax

### ISSUE THREAD

**Issue by Carbon401** [eric-wieser/sublime-bottle#1]
The syntax works fine except for this case: `{{ a if b else c }} ` where somehow the }} doesn't close the python syntax and it continues until the end of the template.

**Comment by Carbon401** [comment]
Commenting `# - include: "Python.sublime-syntax"` under - match: "{{" seems to fix this but of course you won't have proper syntax highlighting for python expressions inside {{ }}.

**Comment by eric-wieser** [comment]
Thanks for the report, got to this eventually - fix was to just include the "expression" part of the python parser rather than the whole thing

**Comment by Carbon401** [comment]
Great! Thanks a lot for the fix
